allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/unenv-preset@2.16.2'
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - miniflare@5.20260921.0-alpha
  - typescript-eslint@8.70.1
  - wrangler@4.136.1
